### ISSUE TITLE
General - Preprocessing - Divide Text into Sections

### ISSUE THREAD

**Issue by JohannesKlueh** [SvenElyes/Textanalytics#6]
For the Creation of Character Association Networks (CAN) the text should be divided into different sections. This may be done on more than one level.
(1) low Level (e.g. Chapters) - since single chapters mark coherent parts of the story / "scenes"
(2) higher level (e.g. groups of 10 chapters)
(3) concluding level - add the CANs of chapter groups (1-10, 1-20, ..., 1 - last chapter)

**Comment by JohannesKlueh** [comment]
Eventually tokenize the Text (as in paper by Varun Nagaraj Rao)

**Comment by fmunzlin** [comment]
The data may already be in an appropriate format - e.g.:

<Book id='10'>
		<Chapter id='1'>
			<Verse id='1'>"Now king David was old and stricken in years; and they covered him[...]"</Verse>
                        ...
			<Verse id='53'>"So king Solomon sent, and they brought him down from the altar. And[...]"</Verse>
		</Chapter>
		<Chapter id='2'>

**Comment by SvenElyes** [comment]
https://github.com/godlytalias/Bible-Database/tree/master/English

**Comment by fmunzlin** [comment]
issue is done by creating the dataloader
