### ISSUE TITLE
Characters - Provide List of Characters

### ISSUE THREAD

**Issue by JohannesKlueh** [SvenElyes/Textanalytics#7]
Create a list of characters for each book of the bible. This should include:
(1) Names of the most important characters
(2) Synonyms for each named character (for co-reference)
(3) List named groups of characters (e.g. "disciples of Jesus")

**Comment by SvenElyes** [comment]
How do we get this list? Do we try to find an already existing one? or do we try to autogenerate it ourselves?

**Comment by JohannesKlueh** [comment]
This is only needed to make work on co-reference resolution possible.
In later project states there should be a named entity recognition in place of the list.

**Comment by SvenElyes** [comment]
We need to a synoym Algorithm, that is able to asssign Synonyms referencing a character in a sentence, which occured before.
